name: build
on:
  push:
    branches:
      master
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - run: ls -asl
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
