name: deployment
on:
  push:
#    branches:
#      - master
jobs:
  build:
    uses: lkwg82/webradio/.github/workflows/build.yml@master
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_PAT: ${{ secrets.deployKey }}
      - name: Updating Domain
        run: echo "Update domain"
