name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
    - name: Install Packages
      run: yarn install
#    - name: Deploy to GH Pages
#      run: |
#        git config --global user.email "deployer@localhost"
#        git config --global user.name "deploy on push"
#        git remote set-url origin https://${{secrets.GITHUB_TOKEN}}@github.com/${{GITHUB_REPOSITORY}}.git 
#        yarn run deploy
    - name: Updating Domain
      run: echo "Update domain"
